2025-03-10 22:17:39 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021D8F7AD700>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2025-03-10 22:17:39 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021D8F7AD490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2025-03-10 22:17:39 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021D8F7AD400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2025-03-10 22:17:39 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021D8F7AD9A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2025-03-10 22:17:39 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021D8F7AD970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
2025-03-10 22:17:39 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021D8F6E1430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /api/4504800232407040/envelope/
