2025-03-11 13:33:52,225 INFO    StreamThr :26684 [internal.py:wandb_internal():86] W&B internal server running at pid: 26684, started at: 2025-03-11 13:33:52.224108
2025-03-11 13:33:52,229 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status
2025-03-11 13:33:52,314 INFO    WriterThread:26684 [datastore.py:open_for_write():85] open: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\run-74um1pnk.wandb
2025-03-11 13:33:52,318 DEBUG   SenderThread:26684 [sender.py:send():382] send: header
2025-03-11 13:33:52,452 DEBUG   SenderThread:26684 [sender.py:send():382] send: run
2025-03-11 13:33:53,170 INFO    SenderThread:26684 [dir_watcher.py:__init__():211] watching files in: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files
2025-03-11 13:33:53,171 INFO    SenderThread:26684 [sender.py:_start_run_threads():1136] run started: 74um1pnk with start time 1741680232.224108
2025-03-11 13:33:53,205 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: check_version
2025-03-11 13:33:53,206 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: check_version
2025-03-11 13:33:53,374 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: run_start
2025-03-11 13:33:54,513 DEBUG   HandlerThread:26684 [system_info.py:__init__():32] System info init
2025-03-11 13:33:54,513 DEBUG   HandlerThread:26684 [system_info.py:__init__():47] System info init done
2025-03-11 13:33:54,513 INFO    HandlerThread:26684 [system_monitor.py:start():194] Starting system monitor
2025-03-11 13:33:54,514 INFO    SystemMonitor:26684 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-03-11 13:33:54,514 INFO    HandlerThread:26684 [system_monitor.py:probe():214] Collecting system info
2025-03-11 13:33:54,521 INFO    SystemMonitor:26684 [interfaces.py:start():190] Started cpu monitoring
2025-03-11 13:33:54,522 INFO    SystemMonitor:26684 [interfaces.py:start():190] Started disk monitoring
2025-03-11 13:33:54,523 INFO    SystemMonitor:26684 [interfaces.py:start():190] Started gpu monitoring
2025-03-11 13:33:54,537 INFO    SystemMonitor:26684 [interfaces.py:start():190] Started memory monitoring
2025-03-11 13:33:54,566 INFO    SystemMonitor:26684 [interfaces.py:start():190] Started network monitoring
2025-03-11 13:33:54,573 DEBUG   HandlerThread:26684 [system_info.py:probe():196] Probing system
2025-03-11 13:33:54,578 DEBUG   HandlerThread:26684 [system_info.py:_probe_git():181] Probing git
2025-03-11 13:33:54,798 DEBUG   HandlerThread:26684 [system_info.py:_probe_git():189] Probing git done
2025-03-11 13:33:54,798 DEBUG   HandlerThread:26684 [system_info.py:probe():244] Probing system done
2025-03-11 13:33:54,798 DEBUG   HandlerThread:26684 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.26100-SP0', 'python': '3.9.5', 'heartbeatAt': '2025-03-11T08:03:54.574199', 'startedAt': '2025-03-11T08:03:52.187248', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'git': {'remote': 'git@github.com-work:saimanikumar-da24m016/da6401_assignment1.git', 'commit': 'e828d7ed826d245b35090fa330e5d4f07dddcfac'}, 'email': 'saimanikumar67@gmail.com', 'root': 'C:/Users/D. Sai Mani Kumar/Downloads/DL/da6401_assignment1', 'host': 'LAPTOP-VRI27UL2', 'username': 'D. Sai Mani Kumar', 'executable': 'c:\\Users\\D. Sai Mani Kumar\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 1500.0, 'min': 0.0, 'max': 2400.0}, 'cpu_freq_per_core': [{'current': 1500.0, 'min': 0.0, 'max': 2400.0}], 'disk': {'/': {'total': 375.82519149780273, 'used': 273.75743103027344}}, 'gpu': 'NVIDIA GeForce GTX 1650 Ti', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1650 Ti', 'memory_total': 4294967296}], 'memory': {'total': 7.840869903564453}}
2025-03-11 13:33:54,798 INFO    HandlerThread:26684 [system_monitor.py:probe():224] Finished collecting system info
2025-03-11 13:33:54,798 INFO    HandlerThread:26684 [system_monitor.py:probe():227] Publishing system info
2025-03-11 13:33:54,798 DEBUG   HandlerThread:26684 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2025-03-11 13:33:54,800 DEBUG   HandlerThread:26684 [system_info.py:_save_pip():68] Saving pip packages done
2025-03-11 13:33:54,802 INFO    HandlerThread:26684 [system_monitor.py:probe():229] Finished publishing system info
2025-03-11 13:33:54,836 DEBUG   SenderThread:26684 [sender.py:send():382] send: files
2025-03-11 13:33:54,836 INFO    SenderThread:26684 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2025-03-11 13:33:54,884 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:33:54,885 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:33:54,888 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:33:55,202 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-metadata.json
2025-03-11 13:33:55,203 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\requirements.txt
2025-03-11 13:33:55,268 DEBUG   SenderThread:26684 [sender.py:send():382] send: telemetry
2025-03-11 13:33:55,269 DEBUG   SenderThread:26684 [sender.py:send():382] send: telemetry
2025-03-11 13:33:55,270 DEBUG   SenderThread:26684 [sender.py:send():382] send: run
2025-03-11 13:33:55,607 INFO    SenderThread:26684 [sender.py:send_run():1010] updated run: 74um1pnk
2025-03-11 13:33:55,891 INFO    wandb-upload_0:26684 [upload_job.py:push():131] Uploaded file C:\Users\D9110~1.SAI\AppData\Local\Temp\tmpwjdt4gojwandb\fqi588zl-wandb-metadata.json
2025-03-11 13:33:56,202 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\config.yaml
2025-03-11 13:33:56,203 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log
2025-03-11 13:33:56,790 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:33:56,790 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:33:57,796 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:33:58,219 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log
2025-03-11 13:33:59,237 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:33:59,238 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:01,684 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:01,685 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:02,855 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:34:04,118 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:04,118 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:06,552 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:06,552 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:07,912 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:34:08,976 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:08,976 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:09,883 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:34:09,884 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:34:09,898 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:34:11,401 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:11,402 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:13,279 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:34:13,822 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:13,823 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:15,369 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:34:15,371 DEBUG   SenderThread:26684 [sender.py:send():382] send: history
2025-03-11 13:34:15,371 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:34:15,376 INFO    SenderThread:26684 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:34:15,408 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-summary.json
2025-03-11 13:34:16,271 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:16,271 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:18,410 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:34:18,444 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log
2025-03-11 13:34:18,702 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:18,703 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:21,132 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:21,133 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:23,491 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:34:23,561 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:23,562 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:24,543 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\config.yaml
2025-03-11 13:34:24,890 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:34:24,891 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:34:24,902 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:34:25,993 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:25,993 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:28,420 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:28,421 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:29,258 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:34:33,410 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:33,412 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:34,295 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:34:35,313 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:34:35,315 DEBUG   SenderThread:26684 [sender.py:send():382] send: history
2025-03-11 13:34:35,316 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:34:35,320 INFO    SenderThread:26684 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:34:35,809 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-summary.json
2025-03-11 13:34:35,810 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log
2025-03-11 13:34:35,855 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:35,856 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:38,301 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:38,302 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:39,373 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:34:39,890 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:34:39,891 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:34:39,892 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:34:40,745 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:40,746 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:43,174 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:43,175 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:45,246 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:34:45,604 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:45,604 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:48,060 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:48,061 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:50,292 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:34:50,479 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:50,480 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:52,899 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:52,900 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:53,286 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:34:53,288 DEBUG   SenderThread:26684 [sender.py:send():382] send: history
2025-03-11 13:34:53,288 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:34:53,291 INFO    SenderThread:26684 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:34:54,218 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-summary.json
2025-03-11 13:34:54,218 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log
2025-03-11 13:34:54,574 DEBUG   SystemMonitor:26684 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-03-11 13:34:54,578 DEBUG   SenderThread:26684 [sender.py:send():382] send: stats
2025-03-11 13:34:54,902 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:34:54,903 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:34:54,904 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:34:55,340 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:55,341 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:56,261 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:34:57,787 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:34:57,788 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:00,218 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:00,219 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:01,353 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:35:02,646 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:02,647 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:05,068 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:05,069 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:06,503 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:35:09,927 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:35:09,928 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:35:09,929 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:35:10,147 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:10,148 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:12,323 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:35:12,654 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:12,654 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:15,106 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:15,107 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:16,520 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:35:16,521 DEBUG   SenderThread:26684 [sender.py:send():382] send: history
2025-03-11 13:35:16,522 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:35:16,526 INFO    SenderThread:26684 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:35:16,755 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-summary.json
2025-03-11 13:35:17,532 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:35:17,547 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:17,547 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:19,225 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log
2025-03-11 13:35:19,977 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:19,977 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:22,411 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:22,413 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:22,740 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:35:24,580 DEBUG   SenderThread:26684 [sender.py:send():382] send: stats
2025-03-11 13:35:24,876 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:24,877 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:24,925 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:35:24,926 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:35:24,927 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:35:27,317 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:27,318 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:28,300 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:35:29,750 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:29,751 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:32,192 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:32,193 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:33,362 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:35:34,636 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:34,637 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:37,069 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:37,070 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:38,443 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:35:39,513 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:39,513 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:39,932 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:35:39,948 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:35:39,949 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:35:41,941 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:41,942 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:44,392 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:35:46,946 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:46,947 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:48,478 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:35:48,480 DEBUG   SenderThread:26684 [sender.py:send():382] send: history
2025-03-11 13:35:48,480 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:35:48,483 INFO    SenderThread:26684 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:35:48,570 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-summary.json
2025-03-11 13:35:49,385 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:49,385 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:49,493 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:35:50,582 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log
2025-03-11 13:35:51,838 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:51,839 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:54,278 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:54,278 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:54,545 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:35:54,589 DEBUG   SenderThread:26684 [sender.py:send():382] send: stats
2025-03-11 13:35:54,929 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:35:54,945 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:35:54,946 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:35:56,731 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:56,732 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:59,156 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:35:59,157 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:00,351 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:36:01,598 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:01,599 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:04,046 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:04,047 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:05,386 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:36:06,486 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:06,487 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:08,927 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:08,927 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:09,952 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:36:09,965 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:36:09,966 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:36:11,326 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:36:13,389 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:13,390 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:16,394 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:36:17,972 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:17,973 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:21,452 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:36:23,103 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:23,104 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:24,604 DEBUG   SenderThread:26684 [sender.py:send():382] send: stats
2025-03-11 13:36:24,964 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:36:24,995 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:36:24,996 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:36:25,526 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:25,527 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:26,067 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:36:26,068 DEBUG   SenderThread:26684 [sender.py:send():382] send: history
2025-03-11 13:36:26,068 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:36:27,552 INFO    SenderThread:26684 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:36:27,554 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:36:27,555 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-summary.json
2025-03-11 13:36:27,555 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log
2025-03-11 13:36:27,991 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:27,991 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:30,429 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:30,429 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:32,654 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:36:32,857 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:32,857 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:35,294 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:35,295 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:37,725 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:36:37,741 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:37,742 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:39,991 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:36:39,998 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:36:40,000 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:36:40,218 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:40,219 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:42,666 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:42,666 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:43,382 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:36:45,107 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:45,108 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:47,559 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:47,560 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:48,433 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:36:50,038 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:50,039 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:52,481 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:52,482 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:53,481 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:36:54,023 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:36:54,025 DEBUG   SenderThread:26684 [sender.py:send():382] send: history
2025-03-11 13:36:54,025 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:36:54,030 INFO    SenderThread:26684 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:36:54,389 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-summary.json
2025-03-11 13:36:54,608 DEBUG   SenderThread:26684 [sender.py:send():382] send: stats
2025-03-11 13:36:54,916 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:54,916 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:55,013 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:36:55,015 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:36:55,017 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:36:55,404 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log
2025-03-11 13:36:58,508 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:36:59,989 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:36:59,990 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:02,429 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:02,430 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:03,507 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:37:04,865 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:04,866 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:07,302 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:07,303 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:08,541 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:37:09,741 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:09,742 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:10,008 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:37:10,008 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:37:10,010 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:37:12,184 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:12,185 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:14,387 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:37:14,618 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:14,618 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:17,057 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:17,058 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:18,517 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:37:18,518 DEBUG   SenderThread:26684 [sender.py:send():382] send: history
2025-03-11 13:37:18,519 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:37:18,524 INFO    SenderThread:26684 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:37:19,084 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-summary.json
2025-03-11 13:37:19,542 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:37:19,574 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:19,575 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:20,091 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log
2025-03-11 13:37:22,007 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:22,008 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:24,444 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:24,445 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:24,599 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:37:24,624 DEBUG   SenderThread:26684 [sender.py:send():382] send: stats
2025-03-11 13:37:25,011 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:37:25,025 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:37:25,026 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:37:26,898 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:26,899 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:29,329 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:29,329 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:30,433 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:37:31,757 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:31,758 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:35,486 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:37:36,774 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:36,774 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:39,199 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:39,200 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:40,011 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:37:40,043 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:37:40,044 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:37:40,595 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:37:41,666 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:41,667 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:41,814 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:37:41,816 DEBUG   SenderThread:26684 [sender.py:send():382] send: history
2025-03-11 13:37:41,816 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:37:41,818 INFO    SenderThread:26684 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:37:42,678 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-summary.json
2025-03-11 13:37:43,734 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log
2025-03-11 13:37:44,174 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:44,175 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:45,832 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:37:46,610 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:46,611 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:49,056 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:49,056 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:50,880 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:37:51,491 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:51,492 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:54,017 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:54,017 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:54,643 DEBUG   SenderThread:26684 [sender.py:send():382] send: stats
2025-03-11 13:37:55,011 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:37:55,042 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: stop_status
2025-03-11 13:37:55,043 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: stop_status
2025-03-11 13:37:56,404 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:37:56,449 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:56,450 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:58,879 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:37:58,880 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:38:01,321 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:38:01,322 ERROR   gpu       :26684 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2025-03-11 13:38:01,445 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:38:01,920 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:38:01,922 DEBUG   SenderThread:26684 [sender.py:send():382] send: history
2025-03-11 13:38:01,922 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:38:01,924 INFO    SenderThread:26684 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:38:02,149 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: partial_history
2025-03-11 13:38:02,151 DEBUG   SenderThread:26684 [sender.py:send():382] send: history
2025-03-11 13:38:02,152 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: summary_record
2025-03-11 13:38:02,154 INFO    SenderThread:26684 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:38:02,155 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-summary.json
2025-03-11 13:38:02,156 DEBUG   SenderThread:26684 [sender.py:send():382] send: telemetry
2025-03-11 13:38:02,204 DEBUG   SenderThread:26684 [sender.py:send():382] send: exit
2025-03-11 13:38:02,206 INFO    SenderThread:26684 [sender.py:send_exit():589] handling exit code: 0
2025-03-11 13:38:02,221 INFO    SenderThread:26684 [sender.py:send_exit():591] handling runtime: 248
2025-03-11 13:38:02,222 INFO    SenderThread:26684 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:38:02,223 INFO    SenderThread:26684 [sender.py:send_exit():597] send defer
2025-03-11 13:38:02,226 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:38:02,226 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 0
2025-03-11 13:38:02,227 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:38:02,227 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 0
2025-03-11 13:38:02,227 INFO    SenderThread:26684 [sender.py:transition_state():617] send defer: 1
2025-03-11 13:38:02,228 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:38:02,228 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 1
2025-03-11 13:38:02,228 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:38:02,228 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 1
2025-03-11 13:38:02,228 INFO    SenderThread:26684 [sender.py:transition_state():617] send defer: 2
2025-03-11 13:38:02,229 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:38:02,229 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 2
2025-03-11 13:38:02,229 INFO    HandlerThread:26684 [system_monitor.py:finish():203] Stopping system monitor
2025-03-11 13:38:02,230 DEBUG   SystemMonitor:26684 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-03-11 13:38:02,231 INFO    HandlerThread:26684 [interfaces.py:finish():202] Joined cpu monitor
2025-03-11 13:38:02,244 DEBUG   SystemMonitor:26684 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-03-11 13:38:02,246 INFO    HandlerThread:26684 [interfaces.py:finish():202] Joined disk monitor
2025-03-11 13:38:02,322 INFO    HandlerThread:26684 [interfaces.py:finish():202] Joined gpu monitor
2025-03-11 13:38:02,323 INFO    HandlerThread:26684 [interfaces.py:finish():202] Joined memory monitor
2025-03-11 13:38:02,325 INFO    HandlerThread:26684 [interfaces.py:finish():202] Joined network monitor
2025-03-11 13:38:02,325 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:38:02,325 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 2
2025-03-11 13:38:02,325 INFO    SenderThread:26684 [sender.py:transition_state():617] send defer: 3
2025-03-11 13:38:02,326 DEBUG   SenderThread:26684 [sender.py:send():382] send: stats
2025-03-11 13:38:02,326 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:38:02,326 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 3
2025-03-11 13:38:02,327 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:38:02,327 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 3
2025-03-11 13:38:02,327 INFO    SenderThread:26684 [sender.py:transition_state():617] send defer: 4
2025-03-11 13:38:02,327 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:38:02,327 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 4
2025-03-11 13:38:02,328 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:38:02,328 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 4
2025-03-11 13:38:02,328 INFO    SenderThread:26684 [sender.py:transition_state():617] send defer: 5
2025-03-11 13:38:02,329 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:38:02,329 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 5
2025-03-11 13:38:02,329 DEBUG   SenderThread:26684 [sender.py:send():382] send: summary
2025-03-11 13:38:02,331 INFO    SenderThread:26684 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2025-03-11 13:38:02,331 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:38:02,332 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 5
2025-03-11 13:38:02,332 INFO    SenderThread:26684 [sender.py:transition_state():617] send defer: 6
2025-03-11 13:38:02,332 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:38:02,332 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 6
2025-03-11 13:38:02,333 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:38:02,333 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 6
2025-03-11 13:38:02,347 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:38:03,168 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-summary.json
2025-03-11 13:38:03,215 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-11 13:38:04,183 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log
2025-03-11 13:38:08,260 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:38:13,301 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:38:18,336 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:38:22,691 WARNING FileStreamThread:26684 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000027AD288DFD0>>, timeout=180), args: ('https://api.wandb.ai/files/da24m016-indian-institute-of-technology-madras/DL_Assignment_01/74um1pnk/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"epoch": 10, "loss": 0.29638529545247505, "accuracy": 0.8927962962962963, "val_loss": 0.3342156348550363, "val_accuracy": 0.8771666666666667, "_timestamp": 1741680482.1376095, "_runtime": 249.91350150108337, "_step": 10, "final_val_loss": 0.3342156348550363, "final_val_accuracy": 0.8771666666666667, "_wandb": {"runtime": 248}}']}, 'wandb-history.jsonl': {'offset': 9, 'content': ['{"epoch": 10, "loss": 0.29638529545247505, "accuracy": 0.8927962962962963, "val_loss": 0.3342156348550363, "val_accuracy": 0.8771666666666667, "_timestamp": 1741680481.9193826, "_runtime": 249.69527459144592, "_step": 9}', '{"final_val_loss": 0.3342156348550363, "final_val_accuracy": 0.8771666666666667, "_timestamp": 1741680482.1376095, "_runtime": 249.91350150108337, "_step": 10}']}, 'wandb-events.jsonl': {'offset': 6, 'content': ['{"system.cpu": 15.38, "system.cpu.0.cpu_percent": 81.97, "system.cpu.1.cpu_percent": 79.92, "system.cpu.2.cpu_percent": 81.33, "system.cpu.3.cpu_percent": 78.7, "system.cpu.4.cpu_percent": 79.93, "system.cpu.5.cpu_percent": 81.33, "system.cpu.6.cpu_percent": 80.35, "system.cpu.7.cpu_percent": 78.88, "system.proc.cpu.threads": 33, "system.disk.\\\\.usagePercent": 73.2, "system.disk.\\\\.usageGB": 275.28, "system.disk.in": 5891.27, "system.disk.out": 3858.6, "system.proc.memory.availableMB": 1197.2, "system.memory": 85.11, "system.proc.memory.rssMB": 439.07, "system.proc.memory.percent": 5.47, "system.network.sent": 3790281.87, "system.network.recv": 107191068.0, "system.gpu.0.memoryAllocated": 3.93, "system.gpu.0.memoryAllocatedBytes": 168820736.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 52.0, "system.gpu.0.powerWatts": 1.7, "system.gpu.0.powerPercent": 5.67, "_wandb": true, "_timestamp": 1741680474.637659, "_runtime": 242.413551}', '{"system.cpu": 16.2, "system.cpu.0.cpu_percent": 78.53, "system.cpu.1.cpu_percent": 76.63, "system.cpu.2.cpu_percent": 76.5, "system.cpu.3.cpu_percent": 72.03, "system.cpu.4.cpu_percent": 68.3, "system.cpu.5.cpu_percent": 66.63, "system.cpu.6.cpu_percent": 68.37, "system.cpu.7.cpu_percent": 71.0, "system.proc.cpu.threads": 33, "system.disk.\\\\.usagePercent": 73.5, "system.disk.\\\\.usageGB": 276.28, "system.disk.in": 9968.46, "system.disk.out": 4619.18, "system.proc.memory.availableMB": 967.73, "system.memory": 87.9, "system.proc.memory.rssMB": 436.79, "system.proc.memory.percent": 5.44, "system.network.sent": 3868816.0, "system.network.recv": 107380699.0, "_wandb": true, "_timestamp": 1741680482.246298, "_runtime": 250.02219}']}, 'output.log': {'offset': 10, 'content': ['2025-03-11T08:08:03.517915 Epoch 10/10: Loss=0.2964, Acc=0.8928, Val Loss=0.3342, Val Acc=0.8772\n']}}, 'dropped': 0}}
2025-03-11 13:38:23,376 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:38:28,408 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:38:33,447 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:38:38,502 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:38:43,556 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:38:46,112 WARNING FileStreamThread:26684 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/da24m016-indian-institute-of-technology-madras/DL_Assignment_01/74um1pnk/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027AD2976160>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000027AD288DFD0>>, timeout=180), args: ('https://api.wandb.ai/files/da24m016-indian-institute-of-technology-madras/DL_Assignment_01/74um1pnk/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"epoch": 10, "loss": 0.29638529545247505, "accuracy": 0.8927962962962963, "val_loss": 0.3342156348550363, "val_accuracy": 0.8771666666666667, "_timestamp": 1741680482.1376095, "_runtime": 249.91350150108337, "_step": 10, "final_val_loss": 0.3342156348550363, "final_val_accuracy": 0.8771666666666667, "_wandb": {"runtime": 248}}']}, 'wandb-history.jsonl': {'offset': 9, 'content': ['{"epoch": 10, "loss": 0.29638529545247505, "accuracy": 0.8927962962962963, "val_loss": 0.3342156348550363, "val_accuracy": 0.8771666666666667, "_timestamp": 1741680481.9193826, "_runtime": 249.69527459144592, "_step": 9}', '{"final_val_loss": 0.3342156348550363, "final_val_accuracy": 0.8771666666666667, "_timestamp": 1741680482.1376095, "_runtime": 249.91350150108337, "_step": 10}']}, 'wandb-events.jsonl': {'offset': 6, 'content': ['{"system.cpu": 15.38, "system.cpu.0.cpu_percent": 81.97, "system.cpu.1.cpu_percent": 79.92, "system.cpu.2.cpu_percent": 81.33, "system.cpu.3.cpu_percent": 78.7, "system.cpu.4.cpu_percent": 79.93, "system.cpu.5.cpu_percent": 81.33, "system.cpu.6.cpu_percent": 80.35, "system.cpu.7.cpu_percent": 78.88, "system.proc.cpu.threads": 33, "system.disk.\\\\.usagePercent": 73.2, "system.disk.\\\\.usageGB": 275.28, "system.disk.in": 5891.27, "system.disk.out": 3858.6, "system.proc.memory.availableMB": 1197.2, "system.memory": 85.11, "system.proc.memory.rssMB": 439.07, "system.proc.memory.percent": 5.47, "system.network.sent": 3790281.87, "system.network.recv": 107191068.0, "system.gpu.0.memoryAllocated": 3.93, "system.gpu.0.memoryAllocatedBytes": 168820736.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 52.0, "system.gpu.0.powerWatts": 1.7, "system.gpu.0.powerPercent": 5.67, "_wandb": true, "_timestamp": 1741680474.637659, "_runtime": 242.413551}', '{"system.cpu": 16.2, "system.cpu.0.cpu_percent": 78.53, "system.cpu.1.cpu_percent": 76.63, "system.cpu.2.cpu_percent": 76.5, "system.cpu.3.cpu_percent": 72.03, "system.cpu.4.cpu_percent": 68.3, "system.cpu.5.cpu_percent": 66.63, "system.cpu.6.cpu_percent": 68.37, "system.cpu.7.cpu_percent": 71.0, "system.proc.cpu.threads": 33, "system.disk.\\\\.usagePercent": 73.5, "system.disk.\\\\.usageGB": 276.28, "system.disk.in": 9968.46, "system.disk.out": 4619.18, "system.proc.memory.availableMB": 967.73, "system.memory": 87.9, "system.proc.memory.rssMB": 436.79, "system.proc.memory.percent": 5.44, "system.network.sent": 3868816.0, "system.network.recv": 107380699.0, "_wandb": true, "_timestamp": 1741680482.246298, "_runtime": 250.02219}']}, 'output.log': {'offset': 10, 'content': ['2025-03-11T08:08:03.517915 Epoch 10/10: Loss=0.2964, Acc=0.8928, Val Loss=0.3342, Val Acc=0.8772\n']}}, 'dropped': 0}}
2025-03-11 13:38:48,609 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:38:53,664 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:38:58,703 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:39:03,757 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:39:08,797 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:39:13,400 INFO    SenderThread:26684 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1061, in _validate_conn
    conn.connect()
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000027AD2984340>, 'Connection to api.wandb.ai timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 802, in urlopen
    retries = retries.increment(
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 594, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027AD2984340>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000027AD2984340>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))
2025-03-11 13:39:13,851 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:39:14,443 WARNING FileStreamThread:26684 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/da24m016-indian-institute-of-technology-madras/DL_Assignment_01/74um1pnk/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027AD29845E0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000027AD288DFD0>>, timeout=180), args: ('https://api.wandb.ai/files/da24m016-indian-institute-of-technology-madras/DL_Assignment_01/74um1pnk/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"epoch": 10, "loss": 0.29638529545247505, "accuracy": 0.8927962962962963, "val_loss": 0.3342156348550363, "val_accuracy": 0.8771666666666667, "_timestamp": 1741680482.1376095, "_runtime": 249.91350150108337, "_step": 10, "final_val_loss": 0.3342156348550363, "final_val_accuracy": 0.8771666666666667, "_wandb": {"runtime": 248}}']}, 'wandb-history.jsonl': {'offset': 9, 'content': ['{"epoch": 10, "loss": 0.29638529545247505, "accuracy": 0.8927962962962963, "val_loss": 0.3342156348550363, "val_accuracy": 0.8771666666666667, "_timestamp": 1741680481.9193826, "_runtime": 249.69527459144592, "_step": 9}', '{"final_val_loss": 0.3342156348550363, "final_val_accuracy": 0.8771666666666667, "_timestamp": 1741680482.1376095, "_runtime": 249.91350150108337, "_step": 10}']}, 'wandb-events.jsonl': {'offset': 6, 'content': ['{"system.cpu": 15.38, "system.cpu.0.cpu_percent": 81.97, "system.cpu.1.cpu_percent": 79.92, "system.cpu.2.cpu_percent": 81.33, "system.cpu.3.cpu_percent": 78.7, "system.cpu.4.cpu_percent": 79.93, "system.cpu.5.cpu_percent": 81.33, "system.cpu.6.cpu_percent": 80.35, "system.cpu.7.cpu_percent": 78.88, "system.proc.cpu.threads": 33, "system.disk.\\\\.usagePercent": 73.2, "system.disk.\\\\.usageGB": 275.28, "system.disk.in": 5891.27, "system.disk.out": 3858.6, "system.proc.memory.availableMB": 1197.2, "system.memory": 85.11, "system.proc.memory.rssMB": 439.07, "system.proc.memory.percent": 5.47, "system.network.sent": 3790281.87, "system.network.recv": 107191068.0, "system.gpu.0.memoryAllocated": 3.93, "system.gpu.0.memoryAllocatedBytes": 168820736.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 52.0, "system.gpu.0.powerWatts": 1.7, "system.gpu.0.powerPercent": 5.67, "_wandb": true, "_timestamp": 1741680474.637659, "_runtime": 242.413551}', '{"system.cpu": 16.2, "system.cpu.0.cpu_percent": 78.53, "system.cpu.1.cpu_percent": 76.63, "system.cpu.2.cpu_percent": 76.5, "system.cpu.3.cpu_percent": 72.03, "system.cpu.4.cpu_percent": 68.3, "system.cpu.5.cpu_percent": 66.63, "system.cpu.6.cpu_percent": 68.37, "system.cpu.7.cpu_percent": 71.0, "system.proc.cpu.threads": 33, "system.disk.\\\\.usagePercent": 73.5, "system.disk.\\\\.usageGB": 276.28, "system.disk.in": 9968.46, "system.disk.out": 4619.18, "system.proc.memory.availableMB": 967.73, "system.memory": 87.9, "system.proc.memory.rssMB": 436.79, "system.proc.memory.percent": 5.44, "system.network.sent": 3868816.0, "system.network.recv": 107380699.0, "_wandb": true, "_timestamp": 1741680482.246298, "_runtime": 250.02219}']}, 'output.log': {'offset': 10, 'content': ['2025-03-11T08:08:03.517915 Epoch 10/10: Loss=0.2964, Acc=0.8928, Val Loss=0.3342, Val Acc=0.8772\n']}}, 'dropped': 0}}
2025-03-11 13:39:18,892 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:39:23,587 WARNING FileStreamThread:26684 [file_stream.py:request_with_retry():668] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/da24m016-indian-institute-of-technology-madras/DL_Assignment_01/74um1pnk/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000027AD2987CD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x0000027AD288DFD0>>, timeout=180), args: ('https://api.wandb.ai/files/da24m016-indian-institute-of-technology-madras/DL_Assignment_01/74um1pnk/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"epoch": 10, "loss": 0.29638529545247505, "accuracy": 0.8927962962962963, "val_loss": 0.3342156348550363, "val_accuracy": 0.8771666666666667, "_timestamp": 1741680482.1376095, "_runtime": 249.91350150108337, "_step": 10, "final_val_loss": 0.3342156348550363, "final_val_accuracy": 0.8771666666666667, "_wandb": {"runtime": 248}}']}, 'wandb-history.jsonl': {'offset': 9, 'content': ['{"epoch": 10, "loss": 0.29638529545247505, "accuracy": 0.8927962962962963, "val_loss": 0.3342156348550363, "val_accuracy": 0.8771666666666667, "_timestamp": 1741680481.9193826, "_runtime": 249.69527459144592, "_step": 9}', '{"final_val_loss": 0.3342156348550363, "final_val_accuracy": 0.8771666666666667, "_timestamp": 1741680482.1376095, "_runtime": 249.91350150108337, "_step": 10}']}, 'wandb-events.jsonl': {'offset': 6, 'content': ['{"system.cpu": 15.38, "system.cpu.0.cpu_percent": 81.97, "system.cpu.1.cpu_percent": 79.92, "system.cpu.2.cpu_percent": 81.33, "system.cpu.3.cpu_percent": 78.7, "system.cpu.4.cpu_percent": 79.93, "system.cpu.5.cpu_percent": 81.33, "system.cpu.6.cpu_percent": 80.35, "system.cpu.7.cpu_percent": 78.88, "system.proc.cpu.threads": 33, "system.disk.\\\\.usagePercent": 73.2, "system.disk.\\\\.usageGB": 275.28, "system.disk.in": 5891.27, "system.disk.out": 3858.6, "system.proc.memory.availableMB": 1197.2, "system.memory": 85.11, "system.proc.memory.rssMB": 439.07, "system.proc.memory.percent": 5.47, "system.network.sent": 3790281.87, "system.network.recv": 107191068.0, "system.gpu.0.memoryAllocated": 3.93, "system.gpu.0.memoryAllocatedBytes": 168820736.0, "system.gpu.0.memory": 0.0, "system.gpu.0.gpu": 0.0, "system.gpu.0.temp": 52.0, "system.gpu.0.powerWatts": 1.7, "system.gpu.0.powerPercent": 5.67, "_wandb": true, "_timestamp": 1741680474.637659, "_runtime": 242.413551}', '{"system.cpu": 16.2, "system.cpu.0.cpu_percent": 78.53, "system.cpu.1.cpu_percent": 76.63, "system.cpu.2.cpu_percent": 76.5, "system.cpu.3.cpu_percent": 72.03, "system.cpu.4.cpu_percent": 68.3, "system.cpu.5.cpu_percent": 66.63, "system.cpu.6.cpu_percent": 68.37, "system.cpu.7.cpu_percent": 71.0, "system.proc.cpu.threads": 33, "system.disk.\\\\.usagePercent": 73.5, "system.disk.\\\\.usageGB": 276.28, "system.disk.in": 9968.46, "system.disk.out": 4619.18, "system.proc.memory.availableMB": 967.73, "system.memory": 87.9, "system.proc.memory.rssMB": 436.79, "system.proc.memory.percent": 5.44, "system.network.sent": 3868816.0, "system.network.recv": 107380699.0, "_wandb": true, "_timestamp": 1741680482.246298, "_runtime": 250.02219}']}, 'output.log': {'offset': 10, 'content': ['2025-03-11T08:08:03.517915 Epoch 10/10: Loss=0.2964, Acc=0.8928, Val Loss=0.3342, Val Acc=0.8772\n']}}, 'dropped': 0}}
2025-03-11 13:39:23,939 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:39:28,563 INFO    SenderThread:26684 [sender.py:transition_state():617] send defer: 7
2025-03-11 13:39:28,565 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: poll_exit
2025-03-11 13:39:28,565 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:39:28,574 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 7
2025-03-11 13:39:28,574 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:39:28,576 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:39:28,576 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 7
2025-03-11 13:39:28,990 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:39:28,991 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-11 13:39:29,145 INFO    Thread-16 :26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\config.yaml
2025-03-11 13:39:29,906 INFO    SenderThread:26684 [sender.py:transition_state():617] send defer: 8
2025-03-11 13:39:29,907 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: poll_exit
2025-03-11 13:39:29,909 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:39:29,910 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 8
2025-03-11 13:39:29,911 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:39:29,911 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 8
2025-03-11 13:39:29,913 INFO    SenderThread:26684 [sender.py:transition_state():617] send defer: 9
2025-03-11 13:39:29,913 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:39:29,914 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 9
2025-03-11 13:39:29,915 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:39:29,915 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 9
2025-03-11 13:39:29,915 INFO    SenderThread:26684 [dir_watcher.py:finish():358] shutting down directory watcher
2025-03-11 13:39:30,106 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-11 13:39:30,157 INFO    SenderThread:26684 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log
2025-03-11 13:39:30,162 INFO    SenderThread:26684 [dir_watcher.py:finish():388] scan: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files
2025-03-11 13:39:30,167 INFO    SenderThread:26684 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\config.yaml config.yaml
2025-03-11 13:39:30,170 INFO    SenderThread:26684 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log output.log
2025-03-11 13:39:30,182 INFO    SenderThread:26684 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\requirements.txt requirements.txt
2025-03-11 13:39:30,210 INFO    SenderThread:26684 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-metadata.json wandb-metadata.json
2025-03-11 13:39:30,211 INFO    SenderThread:26684 [dir_watcher.py:finish():402] scan save: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-summary.json wandb-summary.json
2025-03-11 13:39:30,228 INFO    SenderThread:26684 [sender.py:transition_state():617] send defer: 10
2025-03-11 13:39:30,230 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: poll_exit
2025-03-11 13:39:30,234 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:39:30,248 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 10
2025-03-11 13:39:30,253 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:39:30,259 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 10
2025-03-11 13:39:30,259 INFO    SenderThread:26684 [file_pusher.py:finish():175] shutting down file pusher
2025-03-11 13:39:31,122 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-11 13:39:31,123 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: poll_exit
2025-03-11 13:39:31,208 INFO    wandb-upload_1:26684 [upload_job.py:push():131] Uploaded file c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\output.log
2025-03-11 13:39:31,291 INFO    wandb-upload_2:26684 [upload_job.py:push():131] Uploaded file c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\requirements.txt
2025-03-11 13:39:31,335 INFO    wandb-upload_3:26684 [upload_job.py:push():131] Uploaded file c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\wandb-summary.json
2025-03-11 13:39:31,923 INFO    wandb-upload_0:26684 [upload_job.py:push():131] Uploaded file c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\files\config.yaml
2025-03-11 13:39:32,131 INFO    Thread-15 :26684 [sender.py:transition_state():617] send defer: 11
2025-03-11 13:39:32,132 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:39:32,133 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 11
2025-03-11 13:39:32,133 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-11 13:39:32,134 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:39:32,134 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 11
2025-03-11 13:39:32,134 INFO    SenderThread:26684 [file_pusher.py:join():181] waiting for file pusher
2025-03-11 13:39:32,134 INFO    SenderThread:26684 [sender.py:transition_state():617] send defer: 12
2025-03-11 13:39:32,135 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: poll_exit
2025-03-11 13:39:32,135 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:39:32,135 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 12
2025-03-11 13:39:32,136 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:39:32,136 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 12
2025-03-11 13:39:32,138 INFO    SenderThread:26684 [file_stream.py:finish():595] file stream finish called
2025-03-11 13:39:33,149 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-11 13:39:38,189 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: keepalive
2025-03-11 13:39:41,913 INFO    SenderThread:26684 [file_stream.py:finish():599] file stream finish is done
2025-03-11 13:39:41,914 INFO    SenderThread:26684 [sender.py:transition_state():617] send defer: 13
2025-03-11 13:39:41,914 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: poll_exit
2025-03-11 13:39:41,914 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:39:41,915 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 13
2025-03-11 13:39:41,915 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: status_report
2025-03-11 13:39:41,915 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:39:41,915 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 13
2025-03-11 13:39:41,917 INFO    SenderThread:26684 [sender.py:transition_state():617] send defer: 14
2025-03-11 13:39:41,918 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: defer
2025-03-11 13:39:41,918 DEBUG   SenderThread:26684 [sender.py:send():382] send: final
2025-03-11 13:39:41,918 INFO    HandlerThread:26684 [handler.py:handle_request_defer():172] handle defer: 14
2025-03-11 13:39:41,918 DEBUG   SenderThread:26684 [sender.py:send():382] send: footer
2025-03-11 13:39:41,919 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: defer
2025-03-11 13:39:41,919 INFO    SenderThread:26684 [sender.py:send_request_defer():613] handle sender defer: 14
2025-03-11 13:39:41,921 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: poll_exit
2025-03-11 13:39:41,921 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: poll_exit
2025-03-11 13:39:41,930 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: internal_messages
2025-03-11 13:39:41,932 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: server_info
2025-03-11 13:39:41,933 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: get_summary
2025-03-11 13:39:41,934 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: server_info
2025-03-11 13:39:41,934 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: sampled_history
2025-03-11 13:39:41,940 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: job_info
2025-03-11 13:39:42,216 DEBUG   SenderThread:26684 [sender.py:send_request():409] send_request: job_info
2025-03-11 13:39:42,225 DEBUG   HandlerThread:26684 [handler.py:handle_request():146] handle_request: shutdown
2025-03-11 13:39:42,226 INFO    HandlerThread:26684 [handler.py:finish():866] shutting down handler
2025-03-11 13:39:42,945 INFO    WriterThread:26684 [datastore.py:close():294] close: c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250311_133352-74um1pnk\run-74um1pnk.wandb
2025-03-11 13:39:43,229 INFO    SenderThread:26684 [sender.py:finish():1548] shutting down sender
2025-03-11 13:39:43,230 INFO    SenderThread:26684 [file_pusher.py:finish():175] shutting down file pusher
2025-03-11 13:39:43,230 INFO    SenderThread:26684 [file_pusher.py:join():181] waiting for file pusher
