2025-03-08 03:21:39,337 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2025-03-08 03:21:39,361 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Configure stats pid to 23224
2025-03-08 03:21:39,361 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Loading settings from C:\Users\D. Sai Mani Kumar\.config\wandb\settings
2025-03-08 03:21:39,361 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Loading settings from c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\settings
2025-03-08 03:21:39,362 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-03-08 03:21:39,362 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-03-08 03:21:39,418 INFO    MainThread:23224 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250308_032139-kntuvftq\logs\debug.log
2025-03-08 03:21:39,421 INFO    MainThread:23224 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250308_032139-kntuvftq\logs\debug-internal.log
2025-03-08 03:21:39,421 INFO    MainThread:23224 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000020C471FC1F0>
2025-03-08 03:21:39,464 INFO    MainThread:23224 [wandb_init.py:init():564] calling init triggers
2025-03-08 03:21:39,465 INFO    MainThread:23224 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2025-03-08 03:21:39,466 INFO    MainThread:23224 [wandb_init.py:init():589] re-initializing run, found existing run on stack: 53z5qv1w
2025-03-08 03:21:39,492 INFO    MainThread:23224 [wandb_run.py:_finish():1962] finishing run da24m016-indian-institute-of-technology-madras/my-awesome-project/53z5qv1w
2025-03-08 03:21:39,494 INFO    MainThread:23224 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2025-03-08 03:21:39,505 INFO    MainThread:23224 [wandb_run.py:_restore():2185] restore
2025-03-08 03:21:39,549 INFO    MainThread:23224 [wandb_run.py:_restore():2191] restore done
2025-03-08 03:22:05,679 INFO    MainThread:23224 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2025-03-08 03:22:05,688 INFO    MainThread:23224 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2025-03-08 03:22:05,862 INFO    MainThread:23224 [wandb_run.py:_footer_sync_info():3796] logging synced files
2025-03-08 03:22:07,985 INFO    MainThread:23224 [wandb_init.py:init():614] starting backend
2025-03-08 03:22:07,986 INFO    MainThread:23224 [wandb_init.py:init():618] setting up manager
2025-03-08 03:22:08,041 INFO    MainThread:23224 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2025-03-08 03:22:08,172 INFO    MainThread:23224 [wandb_init.py:init():624] backend started and connected
2025-03-08 03:22:08,942 INFO    MainThread:23224 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2025-03-08 03:22:08,943 INFO    MainThread:23224 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-03-08 03:22:08,943 INFO    MainThread:23224 [wandb_init.py:init():716] updated telemetry
2025-03-08 03:22:09,147 INFO    MainThread:23224 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2025-03-08 03:22:10,377 ERROR   MainThread:23224 [wandb_init.py:init():775] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2025-03-08 03:22:13,458 ERROR   MainThread:23224 [wandb_init.py:init():1188] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 1170, in init
    run = wi.init()
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2025-03-08 03:23:08,030 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2025-03-08 03:23:08,030 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Configure stats pid to 23224
2025-03-08 03:23:08,030 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Loading settings from C:\Users\D. Sai Mani Kumar\.config\wandb\settings
2025-03-08 03:23:08,030 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Loading settings from c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\settings
2025-03-08 03:23:08,031 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-03-08 03:23:08,031 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-03-08 03:23:08,031 INFO    MainThread:23224 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250308_032308-0u0bdrv0\logs\debug.log
2025-03-08 03:23:08,031 INFO    MainThread:23224 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250308_032308-0u0bdrv0\logs\debug-internal.log
2025-03-08 03:23:08,032 INFO    MainThread:23224 [wandb_init.py:init():564] calling init triggers
2025-03-08 03:23:08,032 INFO    MainThread:23224 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2025-03-08 03:23:08,032 INFO    MainThread:23224 [wandb_init.py:init():614] starting backend
2025-03-08 03:23:08,032 INFO    MainThread:23224 [wandb_init.py:init():618] setting up manager
2025-03-08 03:23:08,035 INFO    MainThread:23224 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2025-03-08 03:23:08,039 INFO    MainThread:23224 [wandb_init.py:init():624] backend started and connected
2025-03-08 03:23:08,112 INFO    MainThread:23224 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2025-03-08 03:23:08,113 INFO    MainThread:23224 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-03-08 03:23:08,113 INFO    MainThread:23224 [wandb_init.py:init():716] updated telemetry
2025-03-08 03:23:08,239 INFO    MainThread:23224 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2025-03-08 03:23:24,411 WARNING MainThread:23224 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 1170, in init
    run = wi.init()
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\wandb_init.py", line 752, in init
    result = run_init_handle.wait(
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "c:\Users\D. Sai Mani Kumar\AppData\Local\Programs\Python\Python39\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2025-03-08 03:23:47,912 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2025-03-08 03:23:47,913 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Configure stats pid to 23224
2025-03-08 03:23:47,913 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Loading settings from C:\Users\D. Sai Mani Kumar\.config\wandb\settings
2025-03-08 03:23:47,913 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Loading settings from c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\settings
2025-03-08 03:23:47,913 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-03-08 03:23:47,914 INFO    MainThread:23224 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-03-08 03:23:47,915 INFO    MainThread:23224 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250308_032347-fzca4b8k\logs\debug.log
2025-03-08 03:23:47,915 INFO    MainThread:23224 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\D. Sai Mani Kumar\Downloads\DL\da6401_assignment1\wandb\run-20250308_032347-fzca4b8k\logs\debug-internal.log
2025-03-08 03:23:47,916 INFO    MainThread:23224 [wandb_init.py:init():564] calling init triggers
2025-03-08 03:23:47,916 INFO    MainThread:23224 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2025-03-08 03:23:47,916 INFO    MainThread:23224 [wandb_init.py:init():614] starting backend
2025-03-08 03:23:47,916 INFO    MainThread:23224 [wandb_init.py:init():618] setting up manager
2025-03-08 03:23:47,921 INFO    MainThread:23224 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2025-03-08 03:23:47,942 INFO    MainThread:23224 [wandb_init.py:init():624] backend started and connected
2025-03-08 03:23:48,001 INFO    MainThread:23224 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2025-03-08 03:23:48,002 INFO    MainThread:23224 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-03-08 03:23:48,002 INFO    MainThread:23224 [wandb_init.py:init():716] updated telemetry
2025-03-08 03:23:49,744 INFO    MainThread:23224 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2025-03-08 03:23:50,431 INFO    MainThread:23224 [wandb_run.py:_on_init():2254] communicating current version
2025-03-08 03:24:20,753 INFO    MainThread:23224 [wandb_init.py:init():800] starting run threads in backend
2025-03-08 03:24:21,022 INFO    MainThread:23224 [wandb_run.py:_console_start():2233] atexit reg
2025-03-08 03:24:21,022 INFO    MainThread:23224 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2025-03-08 03:24:21,023 INFO    MainThread:23224 [wandb_run.py:_redirect():2153] Wrapping output streams.
2025-03-08 03:24:21,023 INFO    MainThread:23224 [wandb_run.py:_redirect():2178] Redirects installed.
2025-03-08 03:24:21,025 INFO    MainThread:23224 [wandb_init.py:init():841] run started, returning control to user process
2025-03-08 03:24:21,027 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set learning_rate = 0.001 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,028 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb learning_rate 0.001 None
2025-03-08 03:24:21,029 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set batch_size = 32 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,029 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb batch_size 32 None
2025-03-08 03:24:21,030 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set epochs = 5 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,030 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb epochs 5 None
2025-03-08 03:24:21,031 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set num_layers = 2 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,032 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb num_layers 2 None
2025-03-08 03:24:21,033 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set hidden_size = 64 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,033 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb hidden_size 64 None
2025-03-08 03:24:21,034 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set activation = relu - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,034 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb activation relu None
2025-03-08 03:24:21,035 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set weight_init = xavier - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,035 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb weight_init xavier None
2025-03-08 03:24:21,036 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set loss = cross_entropy - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,036 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb loss cross_entropy None
2025-03-08 03:24:21,037 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set optimizer = adam - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,037 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb optimizer adam None
2025-03-08 03:24:21,038 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set momentum = 0.9 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,038 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb momentum 0.9 None
2025-03-08 03:24:21,038 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set beta = 0.9 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,038 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb beta 0.9 None
2025-03-08 03:24:21,039 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set beta1 = 0.9 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,039 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb beta1 0.9 None
2025-03-08 03:24:21,039 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set beta2 = 0.999 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,040 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb beta2 0.999 None
2025-03-08 03:24:21,040 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set epsilon = 1e-08 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,040 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb epsilon 1e-08 None
2025-03-08 03:24:21,041 INFO    MainThread:23224 [wandb_config.py:__setitem__():151] config set weight_decay = 0.0001 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000020C5F0E0340>>
2025-03-08 03:24:21,041 INFO    MainThread:23224 [wandb_run.py:_config_callback():1342] config_cb weight_decay 0.0001 None
2025-03-08 03:24:51,078 WARNING MsgRouterThr:23224 [router.py:message_loop():77] message_loop has been closed
2025-03-08 03:25:11,445 INFO    MainThread:23224 [wandb_run.py:_finish():1962] finishing run da24m016-indian-institute-of-technology-madras/DL_Assignment_01/fzca4b8k
2025-03-08 03:25:11,447 INFO    MainThread:23224 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2025-03-08 03:25:11,448 INFO    MainThread:23224 [wandb_run.py:_restore():2185] restore
2025-03-08 03:25:11,449 INFO    MainThread:23224 [wandb_run.py:_restore():2191] restore done
2025-03-08 03:41:37,474 INFO    MainThread:23224 [pyagent.py:run():314] Starting sweep agent: entity=None, project=None, count=20
